site_name: Vaultx
site_description: Python 3.x httpx client for HashiCorp's Vault
site_url: https://klukashka.github.io/Vaultx/

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "rgb(73, 123, 167)"
      accent: "rgb(73, 123, 167)"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "rgb(73, 123, 167)"
      accent: "rgb(73, 123, 167)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to light mode"
  features:
  favicon: assets/vaultx_logo.ico

nav:
  - Overview:
      - Welcome to Vaultx: 'index.md'
      - Getting Started: 'overview/getting_started.md'
      - Async Support: 'overview/async_support.md'
      - Why Vaultx: 'overview/why_vaultx.md'
  - Usage:
      - Auth Methods:
          - Token: 'usage/auth_methods/token.md'
          - Userpass: 'usage/auth_methods/userpass.md'
          - AppRole: 'usage/auth_methods/approle.md'
      - Secrets Engines:
          - KV: 'usage/secrets_engines/kv.md'
          - KV-v1: 'usage/secrets_engines/kv_v1.md'
          - KV-v2: 'usage/secrets_engines/kv_v2.md'
      - System Backend:
          - Audit: 'usage/system_backend/audit.md'
          - Auth: 'usage/system_backend/auth.md'
          - Capabilities: 'usage/system_backend/capabilities.md'
          - Health: 'usage/system_backend/health.md'
          - Key: 'usage/system_backend/key.md'
          - Leader: 'usage/system_backend/leader.md'
          - Lease: 'usage/system_backend/lease.md'
          - Mount: 'usage/system_backend/mount.md'
          - Namespace: 'usage/system_backend/namespace.md'
          - Policies: 'usage/system_backend/policies.md'
          - Policy: 'usage/system_backend/policy.md'
          - Quota: 'usage/system_backend/quota.md'
          - Raft: 'usage/system_backend/raft.md'
          - Seal: 'usage/system_backend/seal.md'
          - Wrapping: 'usage/system_backend/wrapping.md'
  - Contributing:
      - Environment Setup: 'contribute/setup.md'
      - Guidelines: 'contribute/guidelines.md'

watch:
  - vaultx

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

repo_name: klukashka/Vaultx
repo_url: https://github.com/klukashka/Vaultx

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/klukashka/Vaultx
      position: header
