name: Update code coverage

on:
  workflow_run:
    workflows: ["Deploy docs"]
    types:
      - completed

jobs:
  update_coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
        vault-version: ["vault-enterprise=1.6.*+ent"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: 1.8.3

      - name: Install dependencies
        run: poetry install --with dev

      - name: Install Vault and Consul (for integration tests)
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
            | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt update \
            -o Dir::Etc::sourceparts="-" \
            -o APT::Get::List-Cleanup="0" \
            -o Dir::Etc::sourcelist="sources.list.d/hashicorp.list"

          sudo apt install \
            consul=1.19.* \
            ${{ matrix.vault-version }} \
            ;

          # We disble cap_ipc_lock here as its generally incompatabile with GitHub
          # Actions' runtime environments.
          sudo setcap cap_ipc_lock= /usr/bin/vault

      - name: Run tests with coverage
        run: poetry run pytest --cov=vaultx --cov-report=xml --cov-report=term

      - name: Generate coverage badge
        run: poetry run coverage-badge -o coverage.svg -f

      - name: Clone gh-pages branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages

      - name: Copy coverage badge to gh-pages
        run: cp coverage.svg gh-pages/

      - name: Check for changes
        run: |
          cd gh-pages
          git add coverage.svg
          if [ -n "$(git diff --cached --name-only)" ]; then
            git commit -m ':arrow_up: Update coverage badge'
            git push
          else
            echo "No changes to commit"
          fi
